### ISSUE TITLE
Mother spider eggs don't despawn naturally.

### ISSUE THREAD

**Issue by Darkmega18** [mcpecommander/Mobultion-mod#14]
I can tell, because I can see ticking 1s through the ground with my damage indicator meaning there are spiders or something ticking off inside walls and stuff where I can't get to them (and yes, when I go there, there are indeed spider eggs). There's also been several eggs on the plateau near my base for a long time just spawning random spiderps. Might want to nerf that. :V 
They also regenerate REALLY stupid fast, even after they've hit max and grown full sized and started spawning, I thought they were meant to then just remain and spawn stuff but not heal anymore?

**Comment by mcpecommander** [comment]
They are supposed to imitate the spider eggs from the binding of Isaac and they are supposed to keep regenerating but there are tons of nerfs to be done. However the mod is currently under low maintenance mode since I am waiting on the api update. I can not promise a fast solution but you can use the spawn changer to lower the spawn rates or stop them totally for now.

**Comment by Darkmega18** [comment]
I had a feeling thats what you were going for. but given that they spawn from a mob who can put them down constantly and just about anywhere it becomes a bit of an overrun issue eventually. but alright, I'll turn off the mother spiders that spawn those.

**Comment by mcpecommander** [comment]
This mod no longer supports any version than 1.16.5 so I am sorry but no bug fixing, just rewrites.

**Comment by Darkmega18** [comment]
welp, ok. I think I stopped using this anyways somewhere down the line. and I had no idea these were all like 3 years old anyways. :V
