### ISSUE TITLE
Armor does not render on some mobs (ravenous zombie)

### ISSUE THREAD

**Issue by Goldenlion5648** [mcpecommander/Mobultion-mod#18]
I used the armoreable mobs mod to make some mobs spawn with armor. One of which was the super lubricant boots from random things. These boots make the wearer experience very little friction. The ravenous zombie was getting the effect and had the item in hand, but the boots were invisible.

Not sure if this applies to other mobs.

**Comment by mcpecommander** [comment]
That is not a bug, The mobs do not use the normal biped model that is offered by minecraft and will not support any armor, heck it is even almost impossible to support all vanilla armor and I had to recreate my own vanilla armor to put it on the knight zombie (that is why the iron armor texture is different on that one).
I can not support any armor mods due to this but I can cancel other mods from adding their armors to my mobs but I am not working on the mod right now while waiting for the api to be fixed.
