### ISSUE TITLE
Error with Entity.KnightZombie.onLivingUpdate

### ISSUE THREAD

**Issue by DatrixTHLK** [mcpecommander/Mobultion-mod#20]
Hi,

I like this mod a lot due to how many mobs there are and If this has been mentioned in here, than you can disregard, but while I was playing Minecraft hollowing out the inside of a Redwood Tree (Biomes O'Plenty) my game crashed while rendering entites such as Knight Zombies within a battletower (AtomicStrykers Mod) nearby. The game was fine for about 5 minutes before it crashed.

Minecraft: 1.12.2
Forge: 14.23.4.2759
Craftstudio API: 1.0.0.93
Mobultion: 0.4.5

Partial FML Log: https://gist.github.com/DatrixTHLK/5b382c3ecd1cf9b2845502f696ac8f48
Crash Report: https://paste.dimdev.org/ozutefihiv.mccrash

If this is more on Craftstudio's side because of how long it's been since it updated last Let me know and I'll add it if it hasn't been already. If it has I can wait until a fix has been put out. Either way thanks for taking the time out to look into the issue (if you haven't already).

**Comment by mcpecommander** [comment]
Craft studio has not been updated and does not seem that it is going to be updated any time soon, I would like to rewrite the whole mod to get rid of the dependency on Craft studio but I can not right now since I have the biggest exam of life in 4 weeks and I need to study for it so no promises when and for the time being I suggest that you disable the mod because this problem occurs in many mobs and I can not fix it easily.

**Comment by DatrixTHLK** [comment]
I see, I have taken out the mod for the time being. I will not rush you seeing as you have to study. I will be patient. Thanks for the fast response to the issue. I appreciate it!

**Comment by mcpecommander** [comment]
This mod no longer supports any version than 1.16.5 so I am sorry but no bug fixing, just rewrites.

**Comment by DatrixTHLK** [comment]
That's fine I'm in 1.16.5 now anyways. Thanks for getting back with me on it.
