### ISSUE TITLE
when possessing a skeleton from this mod with dissolution it leaves a trail of skeleton remains

### ISSUE THREAD

**Issue by lag42** [mcpecommander/Mobultion-mod#3]
hopefully [these two screenshots](https://imgur.com/a/IV53L) will explain a lot

**Comment by Pyrofab** [comment]
I think I have an idea of what's going on, and I'm fairly sure it's on my side
Edit: maybe not that entirely on my side. What happens is that the original entity is removed from the world, which declares it dead, and then resurrected to make the [proxy entity](https://github.com/Ladysnake/Dissolution/blob/bf6017f641c134d03c855dbddc2903e98e44830d/src/main/java/ladysnake/dissolution/common/entity/minion/EntityGenericMinion.java) behave properly. I guess the issue is that there's something else in your skeletons that's tracking whether they're dead and makes the remains spawn each tick.

**Comment by mcpecommander** [comment]
I will fix that but I do not know if I can release a fix before Saturday, but I will look into that

**Comment by mcpecommander** [comment]
I have been summoning the remains in a fairly inefficient way (quite buggy also). I changed the way they spawn.

**Comment by mcpecommander** [comment]
Fixed it
